project_id: '595509'
api_token: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /i18n/*.arb
    translation: /packages/libtokyo_flutter/lib/l10n/lib_%two_letters_code%.arb