name: libtokyo_example
description: Example of libtokyo being used
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.3.0
  libtokyo_jaspr:
    path: ../

dependency_overrides:
  libtokyo:
    path: ../../libtokyo

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.1
  jaspr_builder: ^0.3.0
  lints: ^2.0.1
