name: libtokyo
description: ExpidusOS's UX/UI design language based around the Tokyo Night colorscheme.
version: 0.1.0
homepage: https://github.com/ExpidusOS/libtokyo
issue_tracker: https://github.com/ExpidusOS/libtokyo/issues

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  test: ^1.24.3
