name: libtokyo_flutter
description: ExpidusOS's UX/UI design language for Flutter.
version: 0.1.0
homepage: https://github.com/ExpidusOS/libtokyo
issue_tracker: https://github.com/ExpidusOS/libtokyo/issues
funding:
  - https://opencollective.com/expidusos

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  material_theme_builder: ^1.0.4
  libtokyo:
    git:
      url: https://github.com/ExpidusOS/libtokyo.git
      path: packages/libtokyo
  flutter_localizations:
    sdk: flutter
  path: ^1.8.3
  intl: ^0.18.0
  filesize: ^2.0.1
  bitsdojo_window: ^0.1.5
  shared_preferences: ^2.1.2
  pubspec: ^2.3.0
  url_launcher: ^6.1.11
  google_fonts: ^5.1.0
  font_awesome_flutter: ^10.7.0

dependency_overrides:
  meta: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: false
  generate: true
  assets:
    - ../libtokyo/data/themes/
