on: push

jobs:
  build:
    strategy:
      matrix:
        arch: [x64]
        channel: [stable]
        target: [linux, windows, macos, web]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
            - os: ubuntu-latest
              target: windows
            - os: ubuntu-latest
              target: macos
            - os: windows-latest
              target: linux
            - os: windows-latest
              target: macos
            - os: macos-latest
              target: windows
            - os: macos-latest
              target: linux
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - uses: subosito/flutter-action@v2
          with:
            cache: true
            channel: ${{ matrix.channel }}
            architecture: ${{ matrix.arch }}
        - run: flutter doctor
        - if: ${{ matrix.target == 'linux' }}
          run: |
            sudo apt-get update -y
            sudo apt-get install -y ninja-build libgtk-3-dev
        - run: flutter pub get
        - run: flutter test
        - if: ${{ matrix.target != 'web' }}
          run: |
            flutter config --enable-${{ matrix.target }}-desktop
            cd example
            flutter build ${{ matrix.target }}
        - if: ${{ matrix.target == 'web' }}
          run: |
            cd example
            flutter build ${{ matrix.target }}
